### ISSUE TITLE
Disable Nock for a spec or a list of specs

### ISSUE THREAD

**Issue by assemmarwan** [edorivai/nock-record#7]
I am trying to test Socket.IO functions in a spec file as well as other files containing HTTP requests using nock-record. The Socket.IO tests fail when run along with the tests but succeed when run alone (targeting one spec file).

Is there a way to disable them for a certain spec files?

**Comment by edorivai** [comment]
I'm not 100% sure that I understand your problem. But my guess is that the interceptors from your HTTP test files are intercepting Socket.IO requests.

This would be because `nock-record` uses [Nock Recordings](https://github.com/nock/nock#recording) under the hood, which uses basic nock interceptors under the hood. They intercept all outbound HTTP requests within a single Node process as long as the recording is active. This cannot be split on a per-file basis, since it's actually overwriting the native `http` module under the hood.

One way you can counteract this would be to run each file in a separate node process. Jest does this by default for example.

**Comment by edorivai** [comment]
I'm going to close this issue, let me know if you have further questions

**Comment by arminrosu** [comment]
> Jest does this by default for example.

@edorivai that is not entirely true. 

I have a test suite (let's call it "public") where one suite makes a request to the internet, and another that gets nocked (let's call it "walled").

If the "walled" suite is executed before the "public", the latter fails with:

```
NetConnectNotAllowedError {
  name: 'NetConnectNotAllowedError',
  code: 'ENETUNREACH',
  message: 'Nock: Disallowed net connect for "acme.com"',
```

This is due to how `jest` handles modules and is a known issue for both [nock](https://github.com/nock/nock/issues/1817#issuecomment-630983914) and [jest](https://github.com/facebook/jest/issues/6814)

Running them in "public" > "walled" sequence with `jest --runInBand` works. Please note, we need `--runInBand` on our CI.

My fix was to call `nock.restore` after my "walled" suites. E.g.:

```ts
import { setupRecorder } from 'nock-record'
import * as nock from 'nock'

// ...
const record = setupRecorder()

describe('sample', () => {
  test('should retrieve user info', async () => {
    const { completeRecording, assertScopesFinished } = await record(
      'github-edorivai'
    )
    const result = await getGithubProfile('edorivai')

    completeRecording()
    assertScopesFinished()

    expect(result).toMatchSnapshot()
  })

  afterAll(() => {
    nock.restore()
  })
})

```

Hope that helps.
